### ISSUE TITLE
Option to avoid Flatpaks?

### ISSUE THREAD

**Issue by STrRedWolf** [TheLinuxITGuy/Toolbox#1]
Is there any option to avoid Flatpaks?  I'd rather not have two competing distribution formats on the same system.  It makes things more... _complicated_.

**Comment by TheLinuxITGuy** [comment]
Unfortunately, there will be a mix. I find that flatpak Lutris seems to work better across different distros that I've tested for example.

I'm doing a big update tonight. Stay tuned.
